#%RAML 1.0 NamedExample
               [
                {
                 "productid": 12,
                 "categoryid": 15,
                 "name": "dell pc",
                 "description": "core I 7",
                 "video_url": "http://url",
                 "price": 7000
                 }
                ]
