#%RAML 1.0
title: craft_online_shopping
description: Craft Rest API Documentation
version: 1.0
types:
  productDataType: !include Datatypes/product.raml
  userdatatype: !include Datatypes/user.raml
  orderdatatype: !include Datatypes/order.raml
  categorydatatype: !include Datatypes/category.raml
securitySchemes:
  basic: !include security/basicauth.raml
traits:
  responses: !include traits/respones.raml
resourceTypes:
  resource: !include resources/postResource.raml
  
/products:
  description: get list of all products
  get:
    queryParameters:
      product_id:
        type: integer
        description: id of the product
        required: false
        example: 7788
      name:
        type: string
        description: name of the product
        maxLength: 8
        minLength: 3
        required: false
        example: Lenovo
    headers:
      connection-type:
      session:
        description: connection sesssion is stored
        type: string
        required: false
    responses:
      200:
        body:
          application/json:
            type: productDataType
            example: !include examples/products.raml
    is:
      - responses         
  /{product_id}:
    description: Get specfic product by id
    get:
      description: basic http status respones
      responses:
        200:
          body:
            application/json:
              type: productDataType
              example: !Include examples/product.raml
                 
      is:
        - responses
                
/users:
  description: create user information
  post:
    body:
      application/json:
        
        example: 
          {
               "username": "Tman",
               "useremail": "anitse12"
          }
  
  type:
    resource:
      exampleReference1:
              {
                "msg": "uid generated"
              }
          
  is:
    - responses

 
/orders:
  
  post:
    body:
      application/json:
        example:
         {
           "user_id": "21",
           "product_name": "Hp",
           "productid": "99"
         }
  type:
    resource:
      exampleReference1:
        {
          "msg": "order placed"
        }
         
  is:
    - responses

/categories:
  get:
    description: Get list of products by category
    queryParameters:
      catagoryname:
        type: string
        required: True
        example: "Computers"
      category_id:
        type: integer
        required: false
        example: 1
    responses:
      200:
        body:
          application/json:
            type: categorydatatype
            example: !Include  examples/categories.raml
               
    is:
      - responses
        
  /{catagory_id}:
    description: Get a specifc product by categoryid
    get:
      responses:
        200:
          body:
            application/json:
              type: categorydatatype
              example: !Include examples/category.raml
                
                
      is:
        - responses


               
                     

                
                
      
   
   
           
        
          

  
    


    
  
    
  