#%RAML 1.0 Extension
extends: craft_online_shopping.raml
usage: for admin tasks
/products:
  get:
  post:
  delete:
  /{product_id}:
    get:
    post:
    put:
    delete:
/users:
  get:
  post:
  put:
  delete:
    