#%RAML 1.0 Extension
extends: craft_online_shopping.raml
usage: for admin purpose
/products:
  get:
  post:
    responses:
      201:
        body:
          application/json:
            example:
              {
                
              }
  delete:
  /{product_id}:
    get:
    post:
    put:
    delete:
/users:
  get:
  post:
  delete:

      
    