#%RAML 1.0 NamedExample
[
               {
               "name": "phones",
               "amount": 2000,
               "categoryId": 9
              },
              {
              "name": "laptopes",
              "amount": 300,
              "categoryId": 8
              },
              {
                "name": "shoes",
                "amount": 400,
                "categoryId": 7
              },
              {
                "name": "books",
                "amount": 200,
                "categoryId": 6
              }
]