#%RAML 1.0 NamedExample
[

              {
               "date": "6-23-2021",
               "order_id": 2,
               "user_id": 34,
               "amount": 3,
               "status": "pending"
              },
              {
              "date": "7-21-2020",
              "order_id": 32,
              "user_id": 8,
              "amount": 200,
              "status": "complete"
            },
            {
              "date": "8-12-2020",
              "order_id": 42,
              "user_id": 9,
              "amount": 100,
              "status": "complete"  
            }
]
