#%RAML 1.0 NamedExample
                {
                  "product_id": 4,
                  "catagory_id": 2,
                "name": "Hp",
                "vido_url": "www.hp.com",
                "description": "cor i7",
                "price": 2000
                }