#%RAML 1.0 NamedExample
categories:
             [{
                "categoryid": 100,
                "name": "Laptops"
              },
              {
                "categoryid": 101,
                "name": "mobiles"
              },
              {
                "categoryid": 102,
                "name": "TV"
              }]