#%RAML 1.0 NamedExample
orders:
              [{
                "order_id": 54,
                "userid": 21,
                "discountid": 0001,
                "adressid": 75010,
                "amount": 6000,
                "status": "ordered"

              },
              {
                "order_id": 55,
                "userid": 21,
                "discountid": 0001,
                "adressid": 75010,
                "amount": 8000,
                "status": "ordered"
          
              }]