#%RAML 1.0 NamedExample
  [{
                "productid": 1,
                "categoryid": 13,
                "name": "Hp",
                "description": "cor I 7",
                "video url": "www.hp.com",
                "price": 7000
              },
              {
                "productid": 2,
                "categoryid": 13,
                "name": "Dell",
                "description": "cor I 3",
                "video url": "www.Dell.com",
                "price": 4000
              }]