#%RAML 1.0 NamedExample
             {
              "productid": 12,
              "categoryid": 15,
              "name": "DELL PC",
              "description": "CORE I 5",
              "video_url": "https://DELL.com",
              "price": 3000
             }