#%RAML 1.0 NamedExample
products:
            [{
              "productid": 12,
              "categoryid": 15,
              "name": "DELL PC",
              "description": "CORE I 5",
              "video_url": "https://DELL.com",
              "price": 3000
             },
             {
              "productid": 10,
              "categoryid": 55,
              "name": "LENOVO PC",
              "description": "CORE I 5",
              "video_url": "https://LEN.com",
              "price": 4000
             }] 