#%RAML 1.0 NamedExample
users:
             [{
                "user_id": 44,
                "username": "Tman"
                
              },
              {
                "user_id": 45,
                "username": "john"
                
              }]