#%RAML 1.0 SecurityScheme
type: Basic Authentication
describedBy:
  headers:
    username:
      description: send user name
      type: string
    password:
      description: send password
      type: string
  
  responses:
    
 
    
