#%RAML 1.0 SecurityScheme
type: OAuth 2.0
description: used token
describedBy:
  headers:
    Authorization: 
      description: user will send a valid token
      type: integer
  queryParameters:
    access_token: 
      description: user will send valid token
      type: integer
  responses:
    403: 
      description: credential is required
    401:
      description: token is incorrect or invalid