#%RAML 1.0 NamedExample
              [
                {
                  "name": "laptop",
                  "category_id": 4321
                },

                {
                  "name": "phone",
                  "category_id": 1234
                },
                {
                  "name": "shose",
                  "category_id": 4567
                }
              ]