#%RAML 1.0 NamedExample
              [
              {
                "product_id": 12,
                "name": "Hp",
                "category_id": 4321,
                "description": "cor i 5",
                "video_url": "www.Hp.com",
                "price": 4000
              },
              {
                "product_id": 22,
                "name": "dell",
                "category_id": 4321,
                "description": "cor i 3",
                "video_url": "www.dell.com",
                "price": 3000 
              },

              {
                "product_id": 32,
                "name": "phone",
                "category_id": 4343,
                "description": "iphone pro",
                "video_url": "www.iphonr.com",
                "price": 2000 
              } 
              ]