#%RAML 1.0 NamedExample
                {
                "product_id": 120,
                "name": "Hp",
                "category_id": 3421,
                "description": "cor i 3",
                "video_url": "www.Hp.com",
                "price": 4000
                }