#%RAML 1.0 NamedExample
        [
          {
            username: "samson",
            email: "sami21@gmail.com"
          },
          {
            username: "davd",
            email: "davd12@yahoo.com"
          },
          {
           username: "alex",
           email: "alex2@gmail.com"
         }
        ]